// Generates content/courses/courses.generated.ts from content/courses/<courseId>/.
// Each course dir holds course.md + NN-<slug>.md lessons. Frontmatter is flat
// (scalars + one-line JSON arrays), same parser rules as gen-learn-content.mjs.
// Run: npm run courses:gen

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DIR = join(HERE, "..", "content", "courses");

const COURSE_SCALARS = ["id", "title", "slug", "description", "level", "metaDescription", "updated"];
const COURSE_NUMS = ["estimatedWeeks"];
const LESSON_SCALARS = ["id", "title", "articleSlug", "updated"];
const LESSON_ARRAYS = ["exerciseIds"];

function unquote(v) {
  v = v.trim();
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) return v.slice(1, -1);
  return v;
}

function parseArray(raw) {
  try { return JSON.parse(raw); }
  catch { return raw.replace(/[[\]"]/g, "").split(",").map((s) => s.trim()).filter(Boolean); }
}

function parse(md, label, scalars, nums, arrays) {
  const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!m) throw new Error(`no frontmatter in ${label}`);
  const [, fmRaw, body] = m;
  const out = { body: body.trim() + "\n" };
  for (const line of fmRaw.split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z][A-Za-z0-9]*):\s*(.*)$/);
    if (!kv) continue;
    const [, key, valRaw] = kv;
    if (scalars.includes(key)) out[key] = unquote(valRaw);
    else if (nums.includes(key)) out[key] = Number(unquote(valRaw)) || 0;
    else if (arrays.includes(key)) out[key] = parseArray(valRaw);
  }
  for (const k of scalars) if (out[k] === undefined) throw new Error(`${label}: missing "${k}"`);
  for (const k of nums) if (out[k] === undefined) out[k] = 0;
  for (const k of arrays) if (out[k] === undefined) out[k] = [];
  return out;
}

const courseDirs = readdirSync(DIR).filter((f) => statSync(join(DIR, f)).isDirectory()).sort();
const courses = courseDirs.map((dir) => {
  const course = parse(readFileSync(join(DIR, dir, "course.md"), "utf8"), `${dir}/course.md`, COURSE_SCALARS, COURSE_NUMS, []);
  if (course.id !== dir) throw new Error(`${dir}/course.md: id "${course.id}" must equal the directory name`);
  const lessonFiles = readdirSync(join(DIR, dir)).filter((f) => /^\d{2}-.+\.md$/.test(f)).sort();
  const lessons = lessonFiles.map((f) => {
    const stem = f.replace(/\.md$/, "");
    const lesson = parse(readFileSync(join(DIR, dir, f), "utf8"), `${dir}/${f}`, LESSON_SCALARS, [], LESSON_ARRAYS);
    if (lesson.id !== stem) throw new Error(`${dir}/${f}: id "${lesson.id}" must equal the filename stem`);
    return lesson;
  });
  const { body, ...rest } = course;
  return { ...rest, body, lessons };
});

const banner = "// AUTO-GENERATED by scripts/gen-courses.mjs — do not edit. Run `npm run courses:gen`.\n";
const ts = banner + 'import type { Course } from "./types";\n\n' + "export const COURSES: Course[] = " + JSON.stringify(courses, null, 2) + ";\n";
writeFileSync(join(DIR, "courses.generated.ts"), ts);
console.log(`generated content/courses/courses.generated.ts (${courses.length} courses, ${courses.reduce((n, c) => n + c.lessons.length, 0)} lessons)`);
